import Header from "@/components/header";
import "../styles/globals.css";

export const metadata = {
  title: "Full Stack Next JS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Header />
        {children}
      </body>
    </html>
  );
}
