import Header from "@/components/header";
import "../styles/globals.css";

export const metadata = {
  title: "Full Stack NextJS ISMAEIL BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  );
}
